#!/usr/bin/env bash
#looping 20 times 
i=1
while [ $i -le 20 ]
do
case $i in 
4)
echo $i
echo "bad luck from China"
((i++))
;;

9)
echo $i
echo "bad luck from Japan"
((i++))
;;
17)
echo $i
echo "bad luck from Italy"
((i++))
;;
esac
echo $i
((i++))
done
