#!/usr/bin/env bash
#file

if [ -e "school" ]
then 
echo "school file exists"
if [ -s "school" ] 
then 
echo "school file exists"
else 
echo "school file does not exist"
fi
if [ -f "school" ] 
then 
echo "school is a regular file"
fi

else 
echo "school file does not exist"
fi

