#!/usr/bin/env bash
#programing stuff

echo $$ > /var/run/myscript.pid

while : 
do
trap 'echo I hate the kill command' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm -rf /var/run/myscript.pid' SIGQUIT
trap 'rm -rf /var/run/myscript.pid' SIGTERM       	
echo "To infinity and beyond"
done

trap 
