#!/usr/bin/env bash
#args
case $1 in 

"start")
./manage_my_process & echo $!  > /var/run/my_process.pid
echo "manage_my_process started"
;;
"stop")
echo "manage_my_process stopped"	
sudo pkill -f "manage_my_process" 
rm -rf "/var/run/my_process.pid"	

;;

"restart")
sudo pkill -f "./manage_my_process"
rm -rf /var/run/my_process.pid
./manage_my_process & echo $!  > /var/run/my_process.pid
echo "manage_my_process restarted"
;;

*) 
echo 'Usage: manage_my_process {start|stop|restart}'
;;

esac
