#!/usr/bin/env bash
#args
case $1 in 

"start")
sh ./manage_my_process	
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"

;;
"stop")
rm "/var/run/my_process.pid"	
pkill -f ./manage_my_process
echo "manage_my_process stopped"
;;

"restart")
pkill -f ./manage_my_process
rm /var/run/my_process.pid
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"
sh ./manage_my_process
;;

*) 
echo 'Usage: manage_my_process {start|stop|restart}'
;;

esac
