#!/usr/bin/env bash
#args
case $1 in 

"start")
./manage_my_process &
echo "$(pgrep -f ./manage_my_process)"  > /var/run/my_process.pid
echo "manage_my_process started"
;;
"stop")
sudo kill "$(/var/run/my_process.pid)" &
sudo rm -rf "/var/run/my_process.pid"	
echo "manage_my_process stopped"
;;

"restart")
pkill -f ./manage_my_process
rm -rf /var/run/my_process.pid
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"
./manage_my_process
;;

*) 
echo 'Usage: manage_my_process {start|stop|restart}'
;;

esac
